packages:

  # concretization preferences
  all:
    compiler: [gcc@8.1.1]
    providers:
      mpi: [spectrum-mpi]

  # system modules externals. Uses explicit paths rather than the modules
  # feature of spack, more robust and simpler in some cases.
  spectrum-mpi:
    modules:
      spectrum-mpi@10.3.1.2-20200121%gcc@8.1.1: spectrum-mpi/10.3.1.2-20200121
      spectrum-mpi@10.3.1.2-20200121%pgi@19.9: spectrum-mpi/10.3.1.2-20200121
    buildable: false

  fftw:
    paths:
      fftw@3.3.8%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/fftw-3.3.8-in2y7enjd3memwrmamnoxvsmx37mse7t
      fftw@3.3.8%pgi@19.9: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/fftw-3.3.8-wri566ow7qlimailhyznou5cfm4h362z

  netlib-lapack:
    paths:
      netlib-lapack@3.8.0%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/netlib-lapack-3.8.0-p74bsneivus4jck562lq7drw2s7i4ytd
      netlib-lapack@3.8.0%pgi@19.9:  /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/netlib-lapack-3.8.0-osgnhlqnprebssng2vsxn3dtgmwfutbb

  netlib-scalapack:
    paths:
      netlib-scalapack@2.0.2%gcc@8.1.1: /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/gcc-8.1.1/netlib-scalapack-2.0.2-7x3lv7z2lzfbe5kfwlt2aajkx4hvmgdm
      netlib-lapack@3.8.0%pgi@19.9:  /sw/summit/.swci/1-compute/opt/spack/20180914/linux-rhel7-ppc64le/pgi-19.9/netlib-lapack-3.8.0-osgnhlqnprebssng2vsxn3dtgmwfutbb

  python:
    paths:
      python@3.7.0anaconda: /sw/summit/python/3.7/anaconda3/5.3.0

  cuda:
    paths:
      cuda@10.1.243: /sw/summit/cuda/10.1.243
    buildable: False

  openssl:
    paths:
      openssl@1.0.2k: /usr
    buildable: False

#  cmake:
#    paths:
#      cmake@3.15.2: /sw/summit/.swci/0-core/opt/spack/20180914/linux-rhel7-ppc64le/gcc-4.8.5/cmake-3.15.2-xit2o3iepxvqbyku77lwcugufilztu7t
#    buildable: False

